---
title: "Tree Differential Expression Analysis"
author: "Danielle Paulson"
date: "July 9, 2020"
output: 
  html_notebook:
    toc: true
    toc_float: true
---

# Load Packages

```{r message = FALSE}
library("Seurat")
library("SingleR")
library("dplyr")
library("tidyr")
library("ggplot2")
library("data.table")
library("magrittr")
library(Matrix)
library("cowplot")
library("tidyverse")
library("uwot")
library("parallel")
library(data.tree)
library(DiagrammeR)
library(rare)
library(data.table)
```

# Load Data

```{r}
GSE145281 <- readRDS("seurat.RDS")
GSE145281
```

# Perform Differential Expression

```{r}
mydeg <- function(GSE145281) {
    exp.curr1 = GSE145281@assays$RNA@counts
    meta.dt1 = GSE145281@meta.data %>%
        as.data.table() %>%
        .[,.(binaryResponse=response, patient=patient)] 
    
    meta.curr = list()
    exp.curr2 = list()
    for(patient in unique(meta.dt1$patient)){
        inx = which(meta.dt1$patient==patient)
        exp.curr2[[patient]] = rowSums(exp.curr1[,inx],na.rm=T)
        meta.curr[[patient]] = meta.dt1[inx[1],]
    }
    meta.dt = do.call(rbind, meta.curr)
    exp.curr = t(do.call(rbind, exp.curr2))
    responders = meta.dt[binaryResponse==1]$patient
    nonresponders = meta.dt[binaryResponse==0]$patient
    deseq.out = Seurat:::DESeq2DETest(data.use=exp.curr[,c(responders,nonresponders)], cells.1=responders, cells.2=nonresponders)
    deseq.dt = deseq.out %>%
        as.data.frame() %>%
        mutate(gene=rownames(.)) %>%
        data.table() %>% 
        .[order(p_val)]
    deseq.dt
}
```

```{r}
deg.root <- mydeg(GSE145281)
deg.root
```
```{r}
deg.root[1, 2]
```

# Find Markers

## All Clusters

```{r}
GSE145281.markers.all <- FindAllMarkers(GSE145281, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
GSE145281.markers.all
```
```{r}
GSE145281.markers.all[1, 7]
```

```{r}
newd <-  GSE145281.markers.all %>% group_by(gene) %>% filter(n()>1) #
newd
```

# Phyper Test for Enrichment

```{r}
deg.root = 18897 (group 1)
GSE145281.markers.all = 4,065 (group 2)
```

```{r}
overlaps <- 0

x = 1
z <- c(1:18897)

while (x <= 4065){
  
for(val in z) {
  if(all(GSE145281.markers.all[x, 7] == deg.root[val, 2])){
  overlaps <- overlaps + 1
  z[-val]
  }
}
x = x + 1
}
print(overlaps)
```

```{r}
intersect(GSE145281.markers.all[, 7], deg.root[, 2])
```


```{r}
phyper(Overlap-1, group2, Total-group2, group1,lower.tail= FALSE)
```

# Confirm with Fisher Test

```{r}
fisher.test(matrix(c(Overlap, group2-Overlap, group1-Overlap, Total-group2-group1 +Overlap), 2, 2), alternative='greater')$p.value
```
